version = 1

[[analyzers]]
name = "python"
enabled = true
skip_doc_coverage = ["module", "magic", "init", "class"]

  [analyzers.meta]
  runtime_version = "3.x.x"

[[transformers]]
name = "black"
enabled = true
